modLoader="javafml"
loaderVersion="[47,)"
license="All rights reserved"
issueTrackerURL="https://github.com/"

[[mods]]
modId="annihilationblade"
version="2.3.0-1.20.1-forge"
displayName="Annihilation Blade · Terminus"
authors="青衣_璃"
description='''
§5Annihilation Blade · Terminus
§7A forbidden SlashBlade forged from void, causality and the silence after all stars.
§d
Features:
- Spatial Fracture SA
- Severed Space / World Rift / Terminus Echo SE
- Absolute execution, absolute aegis, void flight
'''
logoFile="icon.png"


[[dependencies.annihilationblade]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.annihilationblade]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.annihilationblade]]
modId="slashblade"
mandatory=true
versionRange="[0.0.1,)"
ordering="NONE"
side="BOTH"

[[mixins]]
    type = "FML"
    config = "annihilationblade.mixins.json"
